### ISSUE TITLE
Sign up and login page api requests 

### ISSUE THREAD

**Issue by aydinmustafacan** [bounswe/2021SpringGroup8#104]
Api requests for sign up and login functionalities from frontend to  backend needs implementation.  Existing frontend need to be enhanced with axios api get and post requests' implementation.

**Comment by faruknane** [comment]
I m going to implement backend APIs. Waiting for @uysalGokhan to implement the Database side.

**Comment by faruknane** [comment]
Can you @aydinmustafacan define the API interface? What parameters are you going to send for login request and what type of response do you want to receive? Can we discuss these?

**Comment by aydinmustafacan** [comment]
endpoint have not been implemented for sign up and login pages. You should define a user object with the fields including username, email,  and password.

**Comment by faruknane** [comment]
@aydinmustafacan We have implemented login and signup endpoints. You can check the [documentation](https://github.com/bounswe/2021SpringGroup8/tree/backend/backend/Endpoints). Feel free to ask questions. Cheers!

**Comment by faruknane** [comment]
@aydinmustafacan if you want to have a test environment, we would like to deploy the code to the server in AWS that we created in the previous term. Please inform us about that!

**Comment by aydinmustafacan** [comment]
It would be better it you were to push your code's docker image to docker hub and we can test the code before deployment that way which would be the best practice. About the api can you implement validation mechanism that makes sure its a valid email. I saw that it checks for username and password but not for email. Also as we have written in project's requirements that we need to hash the password and save it as it is. So that needs implementation as well.  Another issue is that there is no api url to which to send get/post requests in documentation. I would be better if you were to implement that you that frontend team can send requests to those addresses. After you address the issues, can you write a Dockerfile and instructions explaining how to run the backend code so that everyone can run and test it locally.

**Comment by aydinmustafacan** [comment]
You can check out the instructions for the frontend's execution from [here](https://github.com/bounswe/2021SpringGroup8/tree/master/frontend) and write backend's how to run instructions similarly.

**Comment by faruknane** [comment]
- Email validation
- Pass word hashing

I will fix those above. For now, we can keep going with this code since it won't affect the frontend side. I don't want to do anything related to docker since there is no specific installation needed for our code. There are a few libraries that we need which are written in [req.txt](https://github.com/bounswe/2021SpringGroup8/blob/backend/backend/requirements.txt) . I mentioned them in [readme](https://github.com/bounswe/2021SpringGroup8/tree/backend/backend). You may just be able to run server.py file and the server will start at 80 port.

**Comment by faruknane** [comment]
I can run it in AWS if you give me credentials or everyone can run the server in their locals, it is really easy.

**Comment by aydinmustafacan** [comment]
Instructions that you have written doesnt work for me. It gives the error
```
Defaulting to user installation because normal site-packages is not writeable
ERROR: Invalid requirement: 'pip3 install dnspython' (from line 1 of requirements.txt)
```

Docker guarantees that I will work on my system so it is important in  my opinion to dockerize the application.

**Comment by faruknane** [comment]
@aydinmustafacan it might be a special case for you, I don't know about the error.

**Comment by aydinmustafacan** [comment]
Docker wont do the same thing as it does not require anything besides docker itself as dependency and it also is completely independent of the OS that one uses.

**Comment by aydinmustafacan** [comment]
If you were to share docker image in the docker hub i would pull it and run it without any installation in my system

**Comment by faruknane** [comment]
I dont know how to do docker sorry

**Comment by aydinmustafacan** [comment]
Also endpoints that you have written in markdown are unclear. What do you mean by /signup url. Is it http://localhost:80/signup ? 
Please make it clear for others to understand.

**Comment by aydinmustafacan** [comment]
Also I would advise you to write your commit messages as I suggested [here](https://github.com/bounswe/2021SpringGroup8/issues/102) . Looking at your commit when read the commit message I cannot understand what has been implemented easily.

**Comment by faruknane** [comment]
Dude wtf

**Comment by faruknane** [comment]
> Also endpoints that you have written in markdown are unclear

I think they are very well documented.

> Also I would advise you to write your commit messages as I suggested here .When read the commit message I cannot understand what has been implemented easily.

Thanks for the suggestion.

> Instructions that you have written doesnt work for me.

I prepared req.txt by hand that's why you got an error. I fixed it, you may try it again.

**Comment by aydinmustafacan** [comment]
There are some problems with use port 80. It is used with proxy server that we use in frontend thus creates conflict. I suggest you to change it to 8080.

**Comment by aydinmustafacan** [comment]
When I try to send a post request to the server I get the error 
```
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 49486)
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "server.py", line 55, in do_POST
    ProcessRequests.ProcessRequest(self, manager)
  File "/Users/mustafa.aydin/Desktop/deneme/2021SpringGroup8/backend/ProcessRequests.py", line 26, in ProcessRequest
    if ProcessNonTokenRequests(self, manager):
  File "/Users/mustafa.aydin/Desktop/deneme/2021SpringGroup8/backend/ProcessRequests.py", line 42, in ProcessNonTokenRequests
    response = Endpoints.User.SignUp(self, manager, params)
  File "/Users/mustafa.aydin/Desktop/deneme/2021SpringGroup8/backend/Endpoints/User.py", line 55, in SignUp
    username = params["username"][0]
KeyError: 'username'
----------------------------------------
```
Also no helpful response printed to the console.

**Comment by faruknane** [comment]
> It would be better it you were to push your code's 

> You can check out the instructions for the frontend's execution from here and write backend's how to run instructions similarly.

> Also endpoints that you have written in markdown are unclear. What do you mean by /signup url. Is it http://localhost:80/signup ?
Please make it clear for others to understand.

> Also I would advise you to write your commit messages as I suggested here .When read the commit message I cannot understand what has been implemented easily.

> I suggest you to change it to 8080

> Also no helpful response printed to the console.

Dude, I see that you want a lot of things from me, I am feeling annoyed and patronized. It is not nice.

You can just ask nicely like 'can we have any chance to change the port from 80 to 8080 since bla bla'.  Please go make comments on other branches. Leave me free. Thank you.

**Comment by aydinmustafacan** [comment]
@faruknane  I get a similar error when I try to send login request as well.  Apart from that I was able to run the code and thank you for the commit messages that you wrote, made my review easier. I leave the login post request here as well for it to be helpful to you.
```
Exception happened during processing of request from ('127.0.0.1', 49493)
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "server.py", line 55, in do_POST
    ProcessRequests.ProcessRequest(self, manager)
  File "/Users/mustafa.aydin/Desktop/deneme/2021SpringGroup8/backend/ProcessRequests.py", line 26, in ProcessRequest
    if ProcessNonTokenRequests(self, manager):
  File "/Users/mustafa.aydin/Desktop/deneme/2021SpringGroup8/backend/ProcessRequests.py", line 37, in ProcessNonTokenRequests
    response = Endpoints.User.Login(self, manager, params)
  File "/Users/mustafa.aydin/Desktop/deneme/2021SpringGroup8/backend/Endpoints/User.py", line 26, in Login
    username = params["username"][0]
KeyError: 'username'
```

**Comment by aydinmustafacan** [comment]
> > It would be better it you were to push your code's
> 
> > You can check out the instructions for the frontend's execution from here and write backend's how to run instructions similarly.
> 
> > Also endpoints that you have written in markdown are unclear. What do you mean by /signup url. Is it http://localhost:80/signup ?
> > Please make it clear for others to understand.
> 
> > Also I would advise you to write your commit messages as I suggested here .When read the commit message I cannot understand what has been implemented easily.
> 
> > I suggest you to change it to 8080
> 
> > Also no helpful response printed to the console.
> 
> Dude, I see that you want a lot of things from me, I am feeling annoyed and patronized. It is not nice.
> 
> You can just ask nicely like 'can we have any chance to change the port from 80 to 8080 since bla bla'. You are commanding me and I don't find it suitable. Please go make comments on other branches. Leave me free. Thank you.

I gave you a suggestion and did not mean to command you. Also, these issues are everyone of team to remember what kind of problems I face so if they were to face similar kind of problems they can look at the issue and understand it easily.  Apart from that I write here what I found to have chance of being problematic to remember in future so that I were to face similar kind of problems it would be solved easily. Please dont take it personal, i did not referenced to you directly since this issue is assigned to three people and things that I write are for all those three people to solve.

**Comment by faruknane** [comment]
> i did not referenced to you directly 

Lying is a bad thing dude by the way. I advise you not to do it. 

> Changed port address from 80 to 8080

We are getting an error at 8080, we changed it to 80. You are free to change it during your tests.

**Comment by aydinmustafacan** [comment]
> > i did not referenced to you directly 
> 
> Lying is a bad thing dude by the way. I advise you not to do it. 
> 
> > Changed port address from 80 to 8080
> 
> We are getting an error at 8080, we changed it to 80. You are free to change it during your tests.

 I am not lying nor do I have any bad invention. This issue is assigned to me as well as you and Gokhan thus all the comments that I made are for all three of us. When I spot an error I did write here for me to remember as well as others so that it would be easier in the future to solve.

Regarding the error you should not see display on the web page. You need to test it using postman or curl to send post request and check it whether or not it return a response for the login or signup request. Since front end and mobile will handle UI you do not need to see any ui.

**Comment by faruknane** [comment]
> Regarding the error you should not see display on the web page. You need to test it using postman or curl to send post request and check it whether or not it return a response for the login or signup request. Since front end and mobile will handle UI you do not need to see any ui.

I will change it back to 80 when merging into the main branch.
