### ISSUE TITLE
Frontend Branches Should Be Merged

### ISSUE THREAD

**Issue by Physicliar** [bounswe/2021SpringGroup8#107]
There are feature and design branches have been implemented:
1- [Home Page](https://github.com/bounswe/2021SpringGroup8/tree/Origin/Feature%2FHomePage)
2- [Community Page](https://github.com/bounswe/2021SpringGroup8/tree/feature/frontend-community-page)
3- [Sign up and Login](https://github.com/bounswe/2021SpringGroup8/tree/feature/signup-login-android)

These branches should be merged to Frontend branch and then to the main branch.

**Comment by aydinmustafacan** [comment]
In the meeting that we had at [09.11.21](https://github.com/bounswe/2021SpringGroup8/wiki/Meeting-%236-(09.11.2021)) we resolved the conflicts and merged the frontend branches thus closing the issue
