### ISSUE TITLE
Community page's api requests

### ISSUE THREAD

**Issue by aydinmustafacan** [bounswe/2021SpringGroup8#109]
Community page of the frontend needs backend apis to retrieve data related to each post of the community from database. Also, other required functionalities are creating a post in the community which will save all the information about it to database and search functionality enabling users to search for keywords in the posts of the community from all the posts stored in database.  You can check the endpoint that frontend will send requests to from [here](https://github.com/bounswe/2021SpringGroup8/blob/master/frontend/src/services/user-post.service.js)

**Comment by uysalGokhan** [comment]
I created create_community(), delete_community(), get_communities(), get_community_preview(), get_specific_community(), subscribe_to_community(), create_post(), get_posts(), get_post_preview(), get_specific_post() functions for retrieving data from database @faruknane will implement end points after that you can reach endpoints.
