### ISSUE TITLE
Community home page creation for android app

### ISSUE THREAD

**Issue by mssentop** [bounswe/2021SpringGroup8#110]
I'm currently working on the development and implementation of the community home page using Kotlin. Necessary progress milestones will be announced here.

**Comment by mmuhammetcavus** [comment]
I implemented the first draft of the communities page and presented them in the Customer Meeting. When you have a chance you can improve it.

**Comment by mssentop** [comment]
Your implementation was pretty decent. I tested it on my computer as well. I will work on it further.

**Comment by aydinmustafacan** [comment]
Issue seem to have been resolved thus closing it.
