### ISSUE TITLE
Coordination for android team

### ISSUE THREAD

**Issue by mssentop** [bounswe/2021SpringGroup8#111]
We shall arrange a meeting for android development team to share our progress and decide on the design details.

**Comment by mmuhammetcavus** [comment]
I upload first version of the apk of the android app in the [link](https://github.com/bounswe/2021SpringGroup8/tree/feature/signup-login-android/mobile). It welcomes you with a Welcome Page, then from there, you can naviagete to either SignUp Page or Login Page. Once you signed up or logged in the system, it navigates you to Communities Page, where all available communities are listed. Screenshots are available [here](https://github.com/bounswe/2021SpringGroup8/tree/feature/signup-login-android/screenshots). For now login and signup pages only works with local server. where you can [download](https://github.com/bounswe/2021SpringGroup8/tree/backend/backend) and start server in local by running server.py.
But Communities Page does not take any information from any server. Communities list will be empty everytime the code starts. That functionality will be added.

**Comment by aydinmustafacan** [comment]
issue seems to be outdated and redundant thus closing it
