### ISSUE TITLE
Backend Integration for Frontend and Mobile Team

### ISSUE THREAD

**Issue by faruknane** [bounswe/2021SpringGroup8#112]
Hi everyone,

We are planning to finish backend implementation with @uysalGokhan on 13.11.2021 by night ~22-23:00 pm. There will be no obstacle and you may start backend integrations after it is merged into the main branch. There will be documentation for endpoints.

**Comment by uysalGokhan** [comment]
We finished backend implementation with @faruknane and merged with master. We can deploy our backend to AWS if you give necessary informations about our AWS @aydinmustafacan .

**Comment by aydinmustafacan** [comment]
@uysalGokhan Thank you for your effort. I did not preserve Cmpe352's EC2 instance. We need to elect someone to create an AWS EC2 instance. Let's do that in this week's group meeting.
