### ISSUE TITLE
Login&Sign Up mechanisms implemented. 

### ISSUE THREAD

**Issue by aydinmustafacan** [bounswe/2021SpringGroup8#115]
#### Main Implementations :
* Login and sign up functionalities with the help of axios post requests are 
implemented. 
* It implements navbar in the welcome page for theuser to be routed to login page. .
* Structure of the axios requests are made considering the react redux structure thus 
actions, reducers and services directories are all part of the communication mechanism 
between the frontend and backend.
#### Minor implementations:
* Backends Readme.md updated as README.md since it used to include
README.md and Readme.md both which creates collision in non case
sensitive OS.
* Welcome page implemented which now includes navigation bar.
* Profile page implemented showing user's email and id.

 ##### Notes:
* After login application directs user to /profile page and
registers user as loggedIn which makes user logged in until the log out
mechanism is triggered which has yet not been implemented.
* This omits the sign up functionality functions and sign up form's connection
 which will be implemented in future. 

Please check my commit about the changes I made from here a6dc224964dfd4c593a12ba9e8f17fadbd8cf6bf

Reviewers : 

@Physicliar @mmuhammetcavus

**Comment by Physicliar** [comment]
Reviewed the implementations and the functions seems fine. Thank you for styling project. The only thing I notice as warning is that we should be aware of logout mechanism. After backend implementation is finished we should add session mechanism to the application. So it will be helpful for us if we leave a TODO comment inside logout function.
