### ISSUE TITLE
Frontend to backend apis

### ISSUE THREAD

**Issue by aydinmustafacan** [bounswe/2021SpringGroup8#117]
Api request from frontend to backend is not working due to it being sending json object.  Backend only accept www-form-urlencoded objects. So it should be fixed.

**Comment by Physicliar** [comment]
Also the Cross-Origin-Resource-Sharing policy should be fixed, please note it

**Comment by aydinmustafacan** [comment]
Issue has been resolved and became redundant thus closing it.
