### ISSUE TITLE
Unneccessary fields in the SignUp page in web-frontend. 

### ISSUE THREAD

**Issue by mmuhammetcavus** [bounswe/2021SpringGroup8#118]
There are Name and Surname inputs in the SignUp page in the frontend. They have to be removed since in the backend, signUp operation only requires username, email and password. It can be checked which parameters are required for operations in [here](https://github.com/bounswe/2021SpringGroup8/blob/master/backend/Endpoints/Readme.md).

**Comment by aydinmustafacan** [comment]
@Physicliar Emre has developed the sign up page's frontend view. We need his help for this issue to be solved.

**Comment by Physicliar** [comment]
The fields has been fixed now. Please review the commit b217a57a3351964bbd755be422847f8be2336327

**Comment by mmuhammetcavus** [comment]
It is ok now. The fields are nice and good. We can close that issue.
