### ISSUE TITLE
Twitter Logo and Design at the Customer Meeting

### ISSUE THREAD

**Issue by faruknane** [bounswe/2021SpringGroup8#121]
Design pages don't look coherently. Users can't sense a theme. It had two different designs. There were no connectivity among the pages. Twitter logo was terrible. Please make the necessary changes in the frontend. Also, there was no functionality even though it is not integrated with the backend, it should have had it. I "advise" and "suggest" you fix it immediately. It should be fixed. Maybe instead of advising and suggesting directly which is insulting, I could say could you please increase the speed in frontend development.

**Comment by Physicliar** [comment]
Please fix the CORS issue so we can integrate frontend with backend. And please give the feedbacks in the preparations so we can implement before the Customer Demo and milestones.

**Comment by faruknane** [comment]
CORS issue was resolved today as you @Physicliar said in WhatsApp?

**Comment by faruknane** [comment]
Will definetl search about CORS issue 👍🏼

**Comment by aydinmustafacan** [comment]
Above-mentioned problems seem to be resolved thus issue is no longer relevant and needs to be closed.
