### ISSUE TITLE
Team Icon should be placed in "Imgs" Folder

### ISSUE THREAD

**Issue by Physicliar** [bounswe/2021SpringGroup8#123]
During development, there are places where we need the team logo. It can be very useful to put the team logo in the "Imgs" file in order to both pull the team logo from Github directly in the code and download it when needed.

**Comment by mmuhammetcavus** [comment]
We have not determined our offical logo yet. The one that I used in several places in Android app is just a replacement for now. We should determine our logo as soon as possible.

**Comment by aydinmustafacan** [comment]
It is a very good idea to put the logo inside of Imgs folder so that anyone can access it easily and use it according to his needs. Let's determine the logo in next meeting and then we can put it into the folder.

**Comment by aydinmustafacan** [comment]
Logo that everyone in the meeting agreed upon added in the commit 3e68c04c32826451873c4b61bb1d120ee5a5733e
