### ISSUE TITLE
Backend Tasks

### ISSUE THREAD

**Issue by faruknane** [bounswe/2021SpringGroup8#124]
@uysalGokhan @faruknane 

We should implement these below: 
- Backend will implement returning user token after sign up.
- Backend will implement name, surname for sign up. City, birthdate, and profile photo will be added to profile of user
- Update function will be implemented for user profiles in backend.
- Community will not allow users to post without subscription this functionality will be implemented on backend.
- Bug of double subscription on backend will be fixed.

**Comment by uysalGokhan** [comment]
If you not busy at 25.11.2021 after 18:00 we can implement these in a backend meeting

**Comment by faruknane** [comment]
I will be busy around that time (lots of work to do); I am free on 26/27/28.11.2021

**Comment by uysalGokhan** [comment]
ok we can arrange on 26.11.2021 if you want

**Comment by faruknane** [comment]
These are implemented:
* Backend will implement returning user token after sign up.
* Backend will implement name, surname for sign up. City, birthdate, and profile photo will be added to profile of user

**Comment by faruknane** [comment]
The endpoint below is implemented and documented will be written,
* Update function will be implemented for user profiles in backend.

All fields are optional except "@usertoken":

![image](https://user-images.githubusercontent.com/37745467/143677924-f03a5da7-9c92-4f74-ba88-0c217de04711.png)

**Comment by faruknane** [comment]
These are also fixed:
* Community will not allow users to post without subscription this functionality will be implemented on backend.
* Bug of double subscription on backend will be fixed.

@uysalGokhan nice work!
