### ISSUE TITLE
Community post listing and dynamic linking

### ISSUE THREAD

**Issue by aydinmustafacan** [bounswe/2021SpringGroup8#129]
Community post will be listed, and dynamic urls will be generated for each community.

**Comment by Physicliar** [comment]
Related functions are implemented and can be found in the commit c0d9ce6954b995e48108f854db725053aa79f9ec. Please test and review it.
@aydinmustafacan

**Comment by aydinmustafacan** [comment]
I have tested the desired functionalities described in the post and the application delivers all of them. I did not find any bugs. Contributions enhanced the app greatly. This issue is resolved and can now be closed.
