### ISSUE TITLE
Profile page update

### ISSUE THREAD

**Issue by aydinmustafacan** [bounswe/2021SpringGroup8#130]
Profile page will include update name, surname, City, birthdate, and profile photo fields.

**Comment by aydinmustafacan** [comment]
I need the response of the login api extended so as to include name, sirname, city, birthdate, and profile phote
```
 "@return": {
          "username": "sdA12323",
          "id": "618ec90b00bed43ef2daf589",
          "email": "asdasd@asda.com",
          "@type": "User.Object"
```
Can you add above-mentioned fields to the ```@return``` field of login api at ``` http://localhost:8080/login```
@uysalGokhan @faruknane

**Comment by faruknane** [comment]
"@return" field is type of User.Object which contains those properties you mentioned. As far as I know, login endpoint returns the fields you want. Let me check and come back to you @aydinmustafacan

**Comment by aydinmustafacan** [comment]
If it return then I might have had the earlier version and I can proceed to do frontend with the latest version. I'll check again. Please check and let me know and thanks for your quick reply.

**Comment by faruknane** [comment]
I checked it. If you create a new user and use the login endpoint for that user, it will return the fields you specified. We will clear the fields in the documentation since it might create confusion. There will be written something like this "@return": User.Object where you can find the User.Object fields in another section.

**Comment by aydinmustafacan** [comment]
Alrigth, it would be great if you can update documentation when you have time.  Since fields that I mentioned have already been implemented I proceed to implement them in frontend.

**Comment by aydinmustafacan** [comment]
Thank you for the pictures, helped a lot.

**Comment by aydinmustafacan** [comment]
I have implemented a new profile page and updated the login functionality. Now profile page include a top bar inlcuding username of the current user and log out button with log out functionality. Also, profile page will now list more information about the user such as city, name , sirname, username, and email. Related commit is here fe3842194ff4ed3d86c2d49b1ccbf65450a7be8b . Related pull request is [here](https://github.com/bounswe/2021SpringGroup8/pull/135)
Reviewers : @Physicliar @mmuhammetcavus

**Comment by faruknane** [comment]
@aydinmustafacan in the backend brach, in user object we have changed City as Location. From now on, it will be like below:

![image](https://user-images.githubusercontent.com/37745467/145709800-87a1dfa0-d5f6-4400-9556-2d5350d0ef92.png)
![image](https://user-images.githubusercontent.com/37745467/145709805-87d3a265-b91e-4cca-823b-e2762aa65571.png)

Please check [profile update endpoint](https://github.com/bounswe/2021SpringGroup8/tree/backend/backend/Endpoints#update-profile) and [signup endpoint](https://github.com/bounswe/2021SpringGroup8/tree/backend/backend/Endpoints#sign-up).

This location type exits in Data Types as well.

![image](https://user-images.githubusercontent.com/37745467/145709870-7c048cf0-5668-4682-9245-3cdc1f97bd6e.png)
