### ISSUE TITLE
Profile page update mobile 

### ISSUE THREAD

**Issue by aydinmustafacan** [bounswe/2021SpringGroup8#131]
Profile page will include update name, surname, City, birthdate, and profile photo fields and update button for user to update those fields.

**Comment by mmuhammetcavus** [comment]
I updated the signup page, now it has neccesary fields to sign. But profile page is still under impelementation.

**Comment by mmuhammetcavus** [comment]
Profile page is implemented with this [commit](https://github.com/bounswe/2021SpringGroup8/commit/c01c618541c884198d2acdb4ff45dc49fd60baf1) and contains necceesary fields.
