### ISSUE TITLE
Frontend and Backend need to be deployed to AWS and CORS error 

### ISSUE THREAD

**Issue by mmuhammetcavus** [bounswe/2021SpringGroup8#133]
Sİnce we should deploy our server to cloud me and @Physicliar  organized a meeting.  Our new frontend ip adress is : http://3.144.184.237:3000/ and backend server is at http://3.144.184.237:8080/ . We upload server to cloud but deployed version frontend gave corsa error. It should be fixed.

**Comment by Physicliar** [comment]
I found a solution which can solve the problem. The link is:
https://stackoverflow.com/questions/21956683/enable-access-control-on-simple-http-server

please check

**Comment by aydinmustafacan** [comment]
I checked the deployed application in the server and it is healthy and processes working fine. Use of ```nohup``` to run processes seems to be easiest reliable method. Thank you for your effort in the deployment of app to the server @Physicliar . Communication error between the frontend and backend on the server persist. I  leave the error code here for it to be helpful in the solution ```net::ERR_CONNECTION_REFUSED```

**Comment by aydinmustafacan** [comment]
I did deploy the version from the commit fe3842194ff4ed3d86c2d49b1ccbf65450a7be8b in a directory ~/updated/ . While running the application changing api request reference to url address of the server solved the issue. I did changed ```auth.service.js``` file inside of the server to achieve this. If there are no other problems we can say that deployment is successful.
