### ISSUE TITLE
Maps functionality on mobile app

### ISSUE THREAD

**Issue by mmuhammetcavus** [bounswe/2021SpringGroup8#136]
I @mmuhammetcavus  have impelemented maps functionality on mobile app. I user can now open Google Maps window inside app, navigate through the app and select a specific location. But it still not integrated to whole app.

**Comment by mmuhammetcavus** [comment]
I showed you my Google Maps impelentation today. What do you think? Is it gonna be compatible with frontend? @Physicliar @aydinmustafacan

**Comment by aydinmustafacan** [comment]
Apart from one bug that makes the app crash it was very good. If that bug were to resolve I would say that functionality is solid and useful. I would like to follow a similar path for the frontend implementation of the functionality

**Comment by mmuhammetcavus** [comment]
I corrected that error in that [commit](https://github.com/bounswe/2021SpringGroup8/commit/f29c6e9ed9bc52b7d8531fe2b44fdcb6eea7fa16) . Now maps works correctly on mobile app.
