### ISSUE TITLE
Frontend // Community Page is implemented needs to be revised

### ISSUE THREAD

**Issue by Physicliar** [bounswe/2021SpringGroup8#138]
According to project plan community related functionalities and features are implemented. The followings are done:
1- Listed all communities in a page 5d36ad236bd178dec148b40d028d829301ba31d1
2- Show communitiy details c0d9ce6954b995e48108f854db725053aa79f9ec
3- Subscribe to a community f54b7ac828a6c2e99ff9fb1b22794ca1868fa90d
4- Created pull request #137 

The implemented features are needs to be revised, tested and merged to master. Please check @aydinmustafacan @MEHMETTEMIZEL

**Comment by aydinmustafacan** [comment]
I have checked the functionalities implemented in the given commits. Application works fine and functionalities are properly implemented. Since my tests are successful issue can be closed.
