### ISSUE TITLE
New Logo suggestion

### ISSUE THREAD

**Issue by mmuhammetcavus** [bounswe/2021SpringGroup8#144]
If everyone is ok, I suggest to set our app logo as this. I am adding both png and its trasnparent version
![facespace](https://user-images.githubusercontent.com/55928183/145567695-8dbab519-b687-4afe-8a1b-b03eafea2e6d.png)
![facespace (1)](https://user-images.githubusercontent.com/55928183/145567702-0b457b4a-12df-4e9e-8d1a-ce7b649f400f.png)
.

**Comment by aydinmustafacan** [comment]
I think its quite good and nice addition to our application.

**Comment by MEHMETTEMIZEL** [comment]
I like it, I think this logo better than previous suggestion.

**Comment by mmuhammetcavus** [comment]
It seems no one has problem with this new logo. So, our new app logo is set.
