### ISSUE TITLE
Revision of mobile and frontend 

### ISSUE THREAD

**Issue by aydinmustafacan** [bounswe/2021SpringGroup8#149]
Mobile and frontends of the application need to be review in order for it to be in compatible design with each other. They need to have same logos and design principles.

**Comment by mmuhammetcavus** [comment]
We set a meeting (@mmuhammetcavus  and @aydinmustafacan ) together and compared web and mobile application of the project. There are small difference such as mobile does not have image for communities but frontend does. We will make them compatible for milestone2.

**Comment by aydinmustafacan** [comment]
Meeting notes for the above-mentioned meeting can be found [here](https://github.com/bounswe/2021SpringGroup8/wiki/Meeting-11-(11.12.2021))
