### ISSUE TITLE
Choose City API is changed

### ISSUE THREAD

**Issue by mmuhammetcavus** [bounswe/2021SpringGroup8#150]
When a user chooses city in sighnup page, backend stored only name of the city but now, backend wants langitude and lattitude points as well. In android it should be fixed.

**Comment by faruknane** [comment]
Yes, it is also called 'loc' from now on not city. 

I have documented it in backend branch.
![image](https://user-images.githubusercontent.com/37745467/145709710-2da959c4-72d4-4343-bfad-131a3fdea5d4.png)

**Comment by mmuhammetcavus** [comment]
Thanks. Mobile app is now compatible with new response types.
