### ISSUE TITLE
Can we add return to communities page button in community viewing page?

### ISSUE THREAD

**Issue by faruknane** [bounswe/2021SpringGroup8#160]
A user can't go back to the all communities page, can we add a button for that purpose? @Physicliar Thank you. I assigned you since I see you are the only one who gives effort to the project on the front-end side.

![image](https://user-images.githubusercontent.com/37745467/145995943-a95679d6-e57f-44ca-ba56-f67450e43a48.png)

**Comment by Physicliar** [comment]
Navigation bar should be implemented at the frontend side and applied to the pages, so users can navigate easily between pages.

**Comment by aydinmustafacan** [comment]
I have added navigation bar component that I made to that page in this commit : 521f332a33f01842c7da7eadba5d9aa8e425ce90 . Since it achieves desired functionality this issue can be closed.
