### ISSUE TITLE
Frontend // Community Posts Listing is Implemented

### ISSUE THREAD

**Issue by Physicliar** [bounswe/2021SpringGroup8#163]
The feature of community posts listing is implemented and can be found in the commit 01be725602c35c11c07b6fbd4f8df9080588ee37. The followings are details of implemented functions. Please test and review it:
1- Post View Page is created but have a bug on location showing. Also mapping should be added
2- Post service is created
3- Community posts are rendering in the community page with random pics 
4- Post create button is placed but not implemented

**Comment by aydinmustafacan** [comment]
Community page lists the post that are fetched from backend through http request. Post services are implemented with taking  compatibility with the rest of the service into account and coded well. Thank you for your contribution. Issue can now be closed since the implementation is functional.
