### ISSUE TITLE
Frontend // Post Creation is implemented for Community and Needs to be Revised

### ISSUE THREAD

**Issue by Physicliar** [bounswe/2021SpringGroup8#165]
Post creation for community is implemented . It can list the data types of the community and subscriber of the community can choose one of the data types created before. The implementations can be found in the commit 4c708e631744d792f9a63bcf8b6cc38b9597f68f. Please test and review it @aydinmustafacan
Here is the details of the implementation:
1- Create post page is implemented
2- Routes are updated for post creation
3- Default pics are given to the posts but it will  be updated

Details of the commit can be found in the commit message 4c708e631744d792f9a63bcf8b6cc38b9597f68f.

**Comment by aydinmustafacan** [comment]
I tested the functionality for creating posts for the community. It works as intended without bugs. Viewing posts functionality is yet to be implemented once they are created. Since implementation is successful issue can be closed.
