### ISSUE TITLE
Server crashes after running a few days

### ISSUE THREAD

**Issue by mmuhammetcavus** [bounswe/2021SpringGroup8#167]
@faruknane can we review the server to fix it? I cannot reach any api endpoints succesfully. I receive this error.
![image](https://user-images.githubusercontent.com/55928183/146649825-0bb619f2-95b9-4169-8903-b3ae3d45820d.png)
Can we investigate this together?

**Comment by faruknane** [comment]
@mmuhammetcavus Can you come to our discord channel? Let me hear the details from you. Then, we can try fixing it.

**Comment by mmuhammetcavus** [comment]
OK. I am coming to channel.

**Comment by faruknane** [comment]
@mmuhammetcavus I understood the problem, going to fix it in my free time.
![image](https://user-images.githubusercontent.com/37745467/146650706-cb359d2d-deae-492a-95fd-30424d3d06e3.png)

**Comment by aydinmustafacan** [comment]
@mmuhammetcavus 
Can we also write the URL of the server so that each team member can check easily.

**Comment by faruknane** [comment]
I fixed the bug, if it happens again, we can reopen this issue. I'm closing.
