### ISSUE TITLE
Frontend - Search feature should be implemented 

### ISSUE THREAD

**Issue by MEHMETTEMIZEL** [bounswe/2021SpringGroup8#175]
I will implement the search feature for the frontend side with the following properties.
- Community names and descriptions' search
- Posts names, descriptions, data types' search
- Data types will be filtered

**Comment by faruknane** [comment]
How is it going? @MEHMETTEMIZEL 

Could you implement it until tomorrow? We have a customer meeting. Let me know if you need help..

**Comment by faruknane** [comment]
Yes, let's meet tonight at discord.

**Comment by MEHMETTEMIZEL** [comment]
You can go to the [Frontend/Search-feature branch](https://github.com/bounswe/2021SpringGroup8/tree/Frontend/Search-feature) and check the search-feature.
