### ISSUE TITLE
Design - Change navbar background color for better view

### ISSUE THREAD

**Issue by MEHMETTEMIZEL** [bounswe/2021SpringGroup8#176]
Navbar background color and navbar elements' color are almost the same. Different navbar background-color would be better.

**Comment by aydinmustafacan** [comment]
<img width="710" alt="Screen Shot 2021-12-26 at 00 25 20" src="https://user-images.githubusercontent.com/47556889/147393830-9de1a308-d6a9-4abe-80fc-6ae73a1d0e09.png">

It is black on blue and seems readable in the picture that I attach above. What is your suggestion about the color of the navbar.

**Comment by MEHMETTEMIZEL** [comment]
![image](https://user-images.githubusercontent.com/44057947/147704159-1f435277-7c2c-4177-a61e-4471c9bc33fa.png)
I mean the profilebar background should be changed like in the navbar.
