### ISSUE TITLE
Frontend // Mapping Functionality Is Added

### ISSUE THREAD

**Issue by Physicliar** [bounswe/2021SpringGroup8#182]
Mapping functionality is added to post view and and post creation pages. Now users can select a location from map to  get latitude and longitudes of selected place and also users can see selected location in post view page. 

You can find the related commits below:
c1ccd081756610eda2313d8f941090a18779b46b
ae543aa9d80642dac7c67d411f22870de5884347

Please test and review it

**Comment by aydinmustafacan** [comment]
Functionality is working as intended. Users now can add a desired location to their posts. Since implementation is successful issue is resolved and can now be closed.
