### ISSUE TITLE
Advance Search iin database

### ISSUE THREAD

**Issue by uysalGokhan** [bounswe/2021SpringGroup8#183]
We should search communitites with thier names and post with their post data types and with its fields.

**Comment by uysalGokhan** [comment]
I implemented database search functions you can find my commits ids here : 
* d968200e979558a92223463b292b400118dfc2c8
* c478e3b5524d494ac68f34a30993c6adfa2244af
* 361cac4ae8dfdc90946575bbe16d680509fff9f6
* 447a46515590f45cc30eea4c94aac1a7c966c6a3
* b4b9da37b85fb28b4f88620f23095ca7cd430d6c
@faruknane

**Comment by faruknane** [comment]
@uysalGokhan I have also implemented the endpoints using your methods that you have implemented. You may check #184 !
