### ISSUE TITLE
There are conflicts between mobile/editProfile branch and master

### ISSUE THREAD

**Issue by mmuhammetcavus** [bounswe/2021SpringGroup8#209]
We should resolve conflicts between mobile/editProfile branch and master with @mssentop

**Comment by mssentop** [comment]
Lets have a quick discord meeting to resolve them @mmuhammetcavus

**Comment by mmuhammetcavus** [comment]
The conflicts resolved int that [pull request](https://github.com/bounswe/2021SpringGroup8/pull/210) with @mssentop .
