### ISSUE TITLE
Frontend / Advanced Search Post is Implemented Needs to be revised

### ISSUE THREAD

**Issue by Physicliar** [bounswe/2021SpringGroup8#221]
Advanced search for posts is implemented. Now users can make advance search for posts and see them under advance search page. Following are done:
1- Search service is created to interact with the database
2- Dynamic filter renderer is added so users can filter as much as data as they want. 
Please review the commits 
4cc69f69ac05bf894e0fceb9fce22f7b67a658d7
8442d4fedc5355d341cc4a0617ff4758a8e61cec

**Comment by aydinmustafacan** [comment]
I did review the implementation and functionality has successfully been implemented. I didn't find any bugs. Since the relevant commit have been merged to master issue can be closed
