### ISSUE TITLE
Bug in viewing maps in posts

### ISSUE THREAD

**Issue by mssentop** [bounswe/2021SpringGroup8#222]
As mentioned [here](https://github.com/bounswe/2021SpringGroup8/pull/219), there is a bug with maps object while viewing posts. I thought it was a local problem but it appears to be global as it occurred while @mmuhammetcavus was testing as well. It should be resolved.

**Comment by mmuhammetcavus** [comment]
Sometimes locations may be not meaningful. So I added null safe operations on Maps. So it does not crash anymore. It is fixed now with that commit https://github.com/bounswe/2021SpringGroup8/commit/60ebf85823816fb289b6a460fbf146b088623e96 .
