### ISSUE TITLE
Creating a user scenario of posting content and joining a new community

### ISSUE THREAD

**Issue by guneyizol** [bounswe/2021SpringGroup8#23]
We need to create a scenario where a user shares a post in a community but the post is irrelevant to the community. The user is warned about the irrelevance of the post to the community. After that, the user searches for a relevant community and joins  in it.

This scenario needs to be created by 9:00 pm, 18 April 2020.

**Comment by guneyizol** [comment]
The needed scenario is updated to put it in a more meaningful context and reflect another aspect of the user experience.

**Comment by guneyizol** [comment]
> We need to create a scenario where a user shares a post in a community but the post is irrelevant to the community. The user is warned about the irrelevance of the post to the community. After that, the user searches for a relevant community and joins in it.
> 
> This scenario needs to be created by 9:00 pm, 18 April 2020.

The needed scenario is updated to put it in a more meaningful context and reflect another aspect of the user experience.

**Comment by mssentop** [comment]
The scenario is added and can be found [here](https://github.com/bounswe/2021SpringGroup8/wiki/Scenario-%231:-Out-of-Context-Content). The mockup will be prepared later today.

**Comment by mssentop** [comment]
Both scenario and mockup are completed and [here](https://github.com/bounswe/2021SpringGroup8/wiki/Scenario-%231:-Out-of-Context-Content). Closing the issue.
