### ISSUE TITLE
Several reduntant Toasts and dysfunctional parts in Mobile App

### ISSUE THREAD

**Issue by mmuhammetcavus** [bounswe/2021SpringGroup8#245]
There are several Toast Alert Messegas in mobile app. They clearly was used for debugs, but since the project come to an end :(, the reduntant Toasts should be purged.
And also there are some not-implemented features that still visible on mobile app. They also should be purged.

**Comment by mssentop** [comment]
I reviewed and merged your [pull request](https://github.com/bounswe/2021SpringGroup8/pull/246). Now it looks better. Good job!

**Comment by mmuhammetcavus** [comment]
They are removed in that commit https://github.com/bounswe/2021SpringGroup8/pull/246/commits/ffa9cca9f494d496ef70379ad4bc83c58d6cdf7e
