### ISSUE TITLE
Personal wiki pages

### ISSUE THREAD

**Issue by guneyizol** [bounswe/2021SpringGroup8#3]
We need to create and maintain our personal wiki pages.
Please check the box in front of your name if you completed this task.

- [x] Selahaddin Şentop @mssentop 
- [x] Buğra Elmas @cwtaras 
- [x] Akif Faruk Nane @faruknane 
- [x] Muhammet Çavuş @mmuhammetcavus 
- [x] Güney İzol @guneyizol 
- [x] Gökhan Uysal @uysalGokhan 
- [x] Mustafa Can Aydın @aydinmustafacan 
- [x] Ezgi Batı @ezgy

**Comment by aydinmustafacan** [comment]
Everyone has created their personal wiki pages. As a result issue will be closed.
