### ISSUE TITLE
Create sequence diagrams for the project

### ISSUE THREAD

**Issue by mmuhammetcavus** [bounswe/2021SpringGroup8#30]
We should create and draw sequence diagrams.

**Comment by cwtaras** [comment]
![](https://cdn.discordapp.com/attachments/835593564356476978/837389784220958740/Search_Post.jpeg)

**Comment by cwtaras** [comment]
![](https://cdn.discordapp.com/attachments/835593564356476978/837391353255952404/Create_Post.jpeg)

![](https://cdn.discordapp.com/attachments/835593564356476978/837393573648924712/Unfollow_User.jpeg)

**Comment by mmuhammetcavus** [comment]
We created 8 sequence diagram and upload them to [Sequence Diagrams](https://github.com/bounswe/2021SpringGroup8/wiki/Sequence-Diagrams)
