### ISSUE TITLE
Flags and Currency API!

### ISSUE THREAD

**Issue by faruknane** [bounswe/2021SpringGroup8#37]
We should create an API that provides currency exchange rates for the currency community and also provides flags of countries as images. The flags will be used on the sign-up page in case the user chooses a country, the flag will appear.

**Comment by faruknane** [comment]
Unit test for currency exchange can be TRY to TRY always gives 1. Since this is a fact, I can create a unit test for this case.

**Comment by cwtaras** [comment]
Also, you can add comparison between EUR to TRY and TRY to EUR since they are inverse of each other.

**Comment by faruknane** [comment]
Right! @cwtaras that's a good idea. Good job!

**Comment by faruknane** [comment]
Since we merged this API, I am going to close this issue. If anyone has some feedback, you can always reopen and comment.
