### ISSUE TITLE
UI design

### ISSUE THREAD

**Issue by cwtaras** [bounswe/2021SpringGroup8#40]
Add a basic user interface for the created APIs

**Comment by faruknane** [comment]
The assistant said that it would be better if community extra functionalities were implemented on their community page. We can create a few buttons for communities (food community, currency / economy community etc).

**Comment by cwtaras** [comment]
Okay, I will separate API UI's into different URLs which represent the community pages and change my design.

**Comment by cwtaras** [comment]
I finalized the UI design and added all the APIs to the UI with help of my teammates. It is merged to the master.

**Comment by cwtaras** [comment]
I finalized the UI design and added all the APIs to the UI with help of my teammates. It is merged to the master.

**Comment by cwtaras** [comment]
I finalized the UI design and added all the APIs to the UI with help of my teammates. It is merged to the master.
