### ISSUE TITLE
Merging APIs that are ready

### ISSUE THREAD

**Issue by faruknane** [bounswe/2021SpringGroup8#49]
After today's meeting, can we please merge some branches that have already come to their final states? We need to be careful when merging branches. Let's do it after the meeting with those who are free!

**Comment by mssentop** [comment]
Great idea! I am still working on my part but it will indeed be helpful for knowing the steps before hand for the time I complete my own part and apply it for myself.

**Comment by uysalGokhan** [comment]
We can meet at discord if you want.

**Comment by mmuhammetcavus** [comment]
Unittest are missing in my code, I am working on that but it is a good idea to merge the ones that are ready.

**Comment by faruknane** [comment]
Thanks for joining @cwtaras @mssentop @uysalGokhan @mmuhammetcavus @faruknane. We are still continuing to merge branches!

**Comment by cwtaras** [comment]
We have finished merging branches. All APIs are ready, so I think we can close this issue now.
