### ISSUE TITLE
Adding new repositories

### ISSUE THREAD

**Issue by mmuhammetcavus** [bounswe/2021SpringGroup8#5]
Everyone should add their favouirte repositories to [research wiki page](https://github.com/bounswe/2021SpringGroup8/wiki/Github-Repositories)
Check your name if you did.

- [x] Muhammet Çavuş
- [x] Akif Faruk Nane
- [x] Mustafa Can Aydın
- [x] İbrahim Buğra Elmas
- [x] Mehmet Selehattin Şentop
- [x] Güney İzol
- [x] Gökhan Uysal
- [x] Ezgi Batı

**Comment by guneyizol** [comment]
It looks like everyone has added a GitHub repository on the research page.
