### ISSUE TITLE
Team interaction and communication!

### ISSUE THREAD

**Issue by faruknane** [bounswe/2021SpringGroup8#50]
Hi everyone, 

Today we had a meeting with TA. Some of us have understood that it is really important to document and share every detail of progress. To do so, I encourage you to give feedback about our API designs and UI design of @cwtaras. Thank you! 

Not to forget, we should open issues for the tasks that we are assigned so that TA can easily track our progress.

**Comment by uysalGokhan** [comment]
If everybody read this issue I think we can close this issue
