### ISSUE TITLE
Unit Test for search and register user functionalities

### ISSUE THREAD

**Issue by uysalGokhan** [bounswe/2021SpringGroup8#51]
We need unit test case for these functions in case of changing something in the code we can control it quickly with these tests.

**Comment by aydinmustafacan** [comment]
I am currently working on implementing unit tests for it

**Comment by aydinmustafacan** [comment]
Test cases added with the update to the user registration api with the commit dd9fc5fa4c74fbeac2b75a36ee5d8fc131f2f6db
