### ISSUE TITLE
Project Selection Poll

### ISSUE THREAD

**Issue by faruknane** [bounswe/2021SpringGroup8#6]
We have to sort the project ideas from most wanted to least wanted.  In order to do so, as we all decided on each participant has 5 credits for each project (total of 25 credits for 5 projects).  Final sorting will be performed according to the scores that each project gets. This is the method that we all believed would be fair.

Please submit your lists as described below.

Draft: 

| Projects | Credit |
|---------|--------|
|Project 1|0|
|Project 2|0|
|Project 3|0|
|Project 4|0|
|Project 5|0|

<details>
<summary>Click for Markdown Code</summary>
<br>

<pre>
| Projects | Credit |
|---------|--------|
|Project 1|0|
|Project 2|0|
|Project 3|0|
|Project 4|0|
|Project 5|0|
</>
</details>

**Comment by faruknane** [comment]
| Projects | Credit |
|---------|--------|
|Project 1|5|
|Project 2|0|
|Project 3|4|
|Project 4|5|
|Project 5|1|

**Comment by mssentop** [comment]
| Projects | Credit |
|---------|--------|
|Project 1|4|
|Project 2|0|
|Project 3|1|
|Project 4|1|
|Project 5|5|

**Comment by mmuhammetcavus** [comment]
| Projects | Credit |
|---------|--------|
|Project 1|4|
|Project 2|0|
|Project 3|3|
|Project 4|5|
|Project 5|4|

**Comment by ezgy** [comment]
| Projects | Credit |
|---------|--------|
|Project 1|4|
|Project 2|0|
|Project 3|4|
|Project 4|5|
|Project 5|1|

**Comment by uysalGokhan** [comment]
| Projects | Credit |
|---------|--------|
|Project 1|5|
|Project 2|0|
|Project 3|2|
|Project 4|5|
|Project 5|3|

**Comment by guneyizol** [comment]
| Projects | Credit |
|---------|--------|
|Project 1|3|
|Project 2|1|
|Project 3|5|
|Project 4|4|
|Project 5|2|

**Comment by aydinmustafacan** [comment]
| Projects | Credit |
|---------|--------|
|Project 1|3|
|Project 2|1|
|Project 3|2|
|Project 4|5|
|Project 5|5|

**Comment by mssentop** [comment]
Everyone entered their preferences and the choices are decided as 4-1-5-3-2 in decreasing precedence. Issue is closed.
