### ISSUE TITLE
Group Report

### ISSUE THREAD

**Issue by uysalGokhan** [bounswe/2021SpringGroup8#69]
We need to arrange meeting for group report documentation. I think we can arrange at friday at evening. Can you comment about the meeting hour What time it should be ?

**Comment by uysalGokhan** [comment]
We will be meet at 12am.

**Comment by mmuhammetcavus** [comment]
It is good for me and I will be ready at 12 am.

**Comment by faruknane** [comment]
I will attend the meeting as well.

**Comment by mssentop** [comment]
Me too, see you guys in half an hour.

**Comment by mssentop** [comment]
We completed our M2 report and all meetings that demanded our collobarative effort for completing the report. Thus I am closing this issue now.
