### ISSUE TITLE
updating Practice app Documentation wiki

### ISSUE THREAD

**Issue by uysalGokhan** [bounswe/2021SpringGroup8#70]
You should update your apis documentation in this wiki page [here](https://github.com/bounswe/2021SpringGroup8/wiki/Practice-App-Documentation) you can update.

**Comment by mmuhammetcavus** [comment]
I documented create-event page of the practice-app and wrote it into wiki page.

**Comment by faruknane** [comment]
I documented two APIs getflag, getcurrencies -> [getlfag](https://github.com/bounswe/2021SpringGroup8/wiki/Practice-App-Documentation#6getflag) [getcurrencies](https://github.com/bounswe/2021SpringGroup8/wiki/Practice-App-Documentation#7getcurrencies).

**Comment by aydinmustafacan** [comment]
I documented two APIs: [registeruser](https://github.com/bounswe/2021SpringGroup8/wiki/Practice-App-Documentation#3registeruser) and [searchuser](https://github.com/bounswe/2021SpringGroup8/wiki/Practice-App-Documentation#4searchuser).

**Comment by cwtaras** [comment]
I documented my API, [finddistance](https://github.com/bounswe/2021SpringGroup8/wiki/Practice-App-Documentation#9finddistance) .

**Comment by mssentop** [comment]
I documented my API [getquote](https://github.com/bounswe/2021SpringGroup8/wiki/Practice-App-Documentation#8getquote) .

**Comment by mssentop** [comment]
Good work! We completed the documentation of our APIs and even mentioned them in our M2 report. Hence this issue no longer contains any uncompleted task and deserves to be closed.
