### ISSUE TITLE
Updating personal GitHub pages

### ISSUE THREAD

**Issue by aydinmustafacan** [bounswe/2021SpringGroup8#74]
Everyone needs to update his personal GitHub page 

- [x] Mehmet Selahaddin ŞENTOP
- [x] M. Emre DEMİR
- [x] Mehmet TEMİZEL
- [x] Gökhan UYSAL
- [x] Akif Faruk NANE
- [x] Mustafa Can AYDIN
- [x] Muhammet ÇAVUŞ
- [x] İbrahim Buğra ELMAS

**Comment by uysalGokhan** [comment]
@mmuhammetcavus if you updated your personal page can you check the above so we can close this issue

**Comment by mmuhammetcavus** [comment]
I have updated it. I am closing now this issue.
