### ISSUE TITLE
1.1 Functional User Requirements Revision

### ISSUE THREAD

**Issue by Physicliar** [bounswe/2021SpringGroup8#79]
To make more understandable and implementable, functional user requirements shall be updated according the following points:
1- The requirements should be enumerated so they shall be easy to mentionable and hierarchical.
2- Requirements should be clearer and detailed so they shall be understandable and mentionable.
3- Unrelated points should be removed to related parts of requirements.

**Comment by Physicliar** [comment]
Requirements has been changed with. Waiting for group members revision
Revision link: https://github.com/bounswe/2021SpringGroup8/wiki/Requirements/d4c89d5936aff62507d091c58482349f285b6755

**Comment by Physicliar** [comment]
Functional User requirements has been revised and updated according to assistant's and group members feedbacks. 
Revision Link: https://github.com/bounswe/2021SpringGroup8/wiki/Requirements/ad70fa8d86870970bac89f6d663874f725132e9d

Please review
@aydinmustafacan @aydinmustafacan

**Comment by aydinmustafacan** [comment]
Functional user requirements are enhanced according to feedback we have taken from assistant. They have no problems and updated version  seems good. Thus issue can be closed.
