### ISSUE TITLE
Meeting notes of the first week

### ISSUE THREAD

**Issue by aydinmustafacan** [bounswe/2021SpringGroup8#82]
1st meeting notes have been created. Attendees should check it for additional information that might have been omitted. Link to meeting notes: https://github.com/bounswe/2021SpringGroup8/wiki/Meeting-%231

**Comment by Physicliar** [comment]
Meeting plan has been reviewed and communication plan has been updated in meeting notes.
Revision link: https://github.com/bounswe/2021SpringGroup8/wiki/Meeting-%231/bf1165d89d86b17bb4f993f5fff73a546e2b76b2
