### ISSUE TITLE
Research on mobile development

### ISSUE THREAD

**Issue by aydinmustafacan** [bounswe/2021SpringGroup8#88]
Kotlin shall be researched for the mobile development

**Comment by mssentop** [comment]
[This](https://developer.android.com/kotlin?gclid=CjwKCAiAm7OMBhAQEiwArvGi3BxvCA0YJ_cpIFvNlgXwA549RL-h-E0nFO3I5MADdcaXX_8v4ucnbxoCT5oQAvD_BwE&gclsrc=aw.ds)  official documentation and course can also be useful.

**Comment by mssentop** [comment]
There is no longer a need of further research for the tools. Hence I am closing the issue.
