### ISSUE TITLE
Frontend technology research

### ISSUE THREAD

**Issue by aydinmustafacan** [bounswe/2021SpringGroup8#89]
React shall be researched for frontend development

**Comment by aydinmustafacan** [comment]
I advise you to make a research on React redux and react hooks if you do not have any knowledge of these. @Physicliar @MEHMETTEMIZEL

**Comment by MEHMETTEMIZEL** [comment]
> I advise you to make a research on React redux and react hooks if you do not have any knowledge of these. @Physicliar @MEHMETTEMIZEL

https://react-redux.js.org/tutorials/quick-start -> This tutorial can be an introduction to React-Redux.

**Comment by Physicliar** [comment]
Some important advantages of React.JS:
1- Intuitive
2-Declarative
3- Provides Reusable Components
4- JavaScript library
5- Components Support
6- SEO-friendly
7- Proficient Data Binding

SOME ADDITIONAL ADVANTAGES OF REACTJS:
Makes JavaScript coding easier
Extremely competent
Excellent cross-platform support
Handles dependencies
Template designing made easy
Provides amazing developer tools
UI focused designs
Easy to adopt

So it is really good to implement frontend on ReactJs.
