### ISSUE TITLE
Project plan needs update

### ISSUE THREAD

**Issue by aydinmustafacan** [bounswe/2021SpringGroup8#94]
Project plan has to be updated. Link to it : https://github.com/bounswe/2021SpringGroup8/wiki/Project-Plan1

**Comment by uysalGokhan** [comment]
I created project plan from project libre but I need some spesific informations so we can talk it about in next meeting

**Comment by mssentop** [comment]
@uysalGokhan in the last meeting you shared the project plan with the team. If it is ready now can you share it for us to review it?

**Comment by uysalGokhan** [comment]
![image](https://user-images.githubusercontent.com/56603776/142409986-1c0f6917-d08e-452f-9b43-ffc92758c12b.png)
