### ISSUE TITLE
Sign up and login pages for web application

### ISSUE THREAD

**Issue by aydinmustafacan** [bounswe/2021SpringGroup8#95]
Sign up and login pages need development.

**Comment by aydinmustafacan** [comment]
Login page has been made using react. To check it go to  https://github.com/bounswe/2021SpringGroup8/tree/frontend . 
Reviewers : @MEHMETTEMIZEL @Physicliar

**Comment by Physicliar** [comment]
You can make your code more clear understandable and more functional. If you check my last commit regarding sign up page you can find the details and more clearer version of form submission. Please check @aydinmustafacan 
Sign Up commit link: https://github.com/bounswe/2021SpringGroup8/commit/6c71241562d1cfbdb19cde1b3142adcbd7ff606e

**Comment by Physicliar** [comment]
Sign up page has been made using react. To check it please check my last commit https://github.com/bounswe/2021SpringGroup8/commit/6c71241562d1cfbdb19cde1b3142adcbd7ff606e
or go to https://github.com/bounswe/2021SpringGroup8/tree/frontend

Reviewers @MEHMETTEMIZEL @Physicliar

**Comment by aydinmustafacan** [comment]
I have run the application locally and it seems fine. Validation methods are enhanced and made easier with the use of "Yup".  "Formik" also seems to make it easier which can be considered for the future use as well. Also, I liked the css that is used.  Since this feature is now fully implemented I close the issue.
